# Generated by Django 4.2.16 on 2025-03-24 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteArgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('solde', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Groupe_Offrandes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('num_ordre', models.CharField(max_length=100)),
                ('description_recette', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Groupe_Previsions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('num_ordre', models.CharField(max_length=100)),
                ('description_prevision', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sorte_Prevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('num_compte', models.IntegerField(max_length=15)),
                ('nom_prevision', models.TextField(max_length=50)),
                ('descript_prevision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prosfera_App.groupe_previsions')),
            ],
        ),
        migrations.CreateModel(
            name='Sorte_Offrande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('num_compte', models.IntegerField(max_length=15)),
                ('nom_offrande', models.TextField(max_length=50)),
                ('descript_recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prosfera_App.groupe_offrandes')),
            ],
        ),
        migrations.CreateModel(
            name='Prevoir',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant_prevus', models.IntegerField(max_length=15)),
                ('annee_prevus', models.IntegerField(max_length=8)),
                ('descript_prevision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prosfera_App.sorte_prevision')),
            ],
        ),
        migrations.CreateModel(
            name='Payement_Offrande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('departement', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_payement', models.DateField()),
                ('annee', models.IntegerField()),
                ('nom_offrande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prosfera_App.sorte_offrande')),
            ],
        ),
    ]
