# Generated by Django 4.2.16 on 2025-07-06 17:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Prosfera_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etat_Besoin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(default='Rien', max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantite', models.CharField(default='Rien', max_length=25)),
                ('motif', models.CharField(default='Rien', max_length=255)),
            ],
        ),
    ]
