# Generated by Django 4.2.20 on 2025-03-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prosfera_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prevoir',
            name='annee_prevus',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='prevoir',
            name='montant_prevus',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sorte_offrande',
            name='num_compte',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sorte_prevision',
            name='num_compte',
            field=models.IntegerField(),
        ),
    ]
