# Generated by Django 4.2.16 on 2025-07-08 14:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Prosfera_App', '0002_etat_besoin'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtatBesoin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite', models.PositiveIntegerField()),
                ('motif', models.TextField()),
                ('date_etat_besoin', models.DateField(auto_now_add=True)),
                ('validation_pasteur', models.BooleanField(default=False)),
                ('validation_caisse', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Etat_Besoin',
        ),
    ]
