# Generated by Django 4.2.20 on 2025-03-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prosfera_App', '0002_alter_prevoir_annee_prevus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prevoir',
            name='annee_prevus',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='prevoir',
            name='montant_prevus',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='sorte_prevision',
            name='num_compte',
            field=models.BigIntegerField(),
        ),
    ]
