# Generated by Django 4.2.16 on 2025-07-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prosfera_App', '0003_etatbesoin_delete_etat_besoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='etatbesoin',
            name='designation',
            field=models.CharField(default='Aucune désignation', max_length=255),
        ),
        migrations.AlterField(
            model_name='etatbesoin',
            name='quantite',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
