# Generated by Django 4.2.16 on 2025-07-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prosfera_App', '0004_etatbesoin_designation_alter_etatbesoin_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etatbesoin',
            name='quantite',
            field=models.CharField(max_length=100),
        ),
    ]
