# Generated by Django 4.2.20 on 2025-03-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prosfera_App', '0005_alter_payement_offrande_annee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorte_offrande',
            name='num_compte',
            field=models.CharField(max_length=20),
        ),
    ]
